
density:
    bins:               50
    max_points:         500
    min_count:          3
    tessellation:       hex
    cmap:               'cmr.voltage_r'
    alpha:              1

    style:
        marker:     x
        ls:         ''