# ---------------------------------------------------------------------------- #
image:

    plim:           [0.25, 99.75]
    origin:         lower
    interpolation:  none
    blit:   on

    figure:
        size:           auto
        fill:           0.75 # Max fraction of screen size allowed in any direction
        max_pixel_size: 0.2  # Max pixel size allowed in inches
    
        margins:
            left:       0.05
            right:      0.95
            top:        0.98
            bottom:     0.05

    cbar:
        show:       True
        position:   right
        size:       0.2
        pad:        0
    hist:
        show:       True
        position:   right
        size:       0.6
        pad:        0
        bins:       100
    sliders:
        show:           True
        color:          [r, g, b]
        ms:             [2, 1, 2]
        extra_markers:  ['>', s, <]


    modelling:
        image:
            plim:       [0, 100]
            cmap:       cmr.seasons

        bars:
            ec:             "0.6"
            lw:             0.1
            lightsource:    [90, 45]

        image_bar_plot:
            figure:
                size: [8.45, 3.78]
                margins:
                    top: 1.0
                    bottom: 0.05
                    left: 0.05
                    right: 0.95
                    wspace: 0.2
            axes:
                position: [0.35, 0.0, 0.8, 1.1]
                azim: -125
                elev: 30
                zlim: [0, 100]



        axes:
            titles:     [Data, Model, Residual]
            image:
                axes_pad:       0.1
                label_mode:     L
                cbar:
                    mode:       each
                    size:       10%
                    pad:        0%
                    location:   right

                    ticks:
                        labels:
                            weight:     bold
                            ha:         center
                            va:         center
                            # emboss:     [0.5, orangered]

                        major:
                            colors:     orangered
                            direction:  in
                            labelsize:  12
                            pad:        -13
                            length:     4
                        minor:
                            length:     2
                        right:
                            pad:        8
                            direction:  inout
                        

            3d:
                azim:       -125
                elev:       30



# ---------------------------------------------------------------------------- #
video:
    clim_every:     off
    
    scroll:
        wrap:       on
        rate_limit: 10
    
    slider:
        label:      frame
        valfmt:     '%d'
        position:   bottom
        size:       0.1
        pad:        0.3

    features:
        marker_cycle:   XPoHd*s
        s:              25
        alpha:          1
        linewidths:     0.7

    apertures:
        ec: m
        lw: 1

# ---------------------------------------------------------------------------- #
image3d:
    zaxis_cbar:     on

# ---------------------------------------------------------------------------- #
density:
    bins:           50
    max_points:     500
    min_count:      3
    tessellation:   hex
    cmap:           cmr.voltage_r
    alpha:          1

    density:
        # parameters passed to the PolyCollection
        linewidth:      0.25
        # This is needed for the hexbins to be correct with large number of
        #  bins:  see https://github.com/matplotlib/matplotlib/issues/26202

    scatter:
        marker:     x
        ls:         ''

# ---------------------------------------------------------------------------- #
depth:
    prisms:
        dxy:            '0.8'
        cmap:           null

# ---------------------------------------------------------------------------- #
corner:
    
    nbins:      30
    plims:      [0., 100]
    cmap:       cmr.voltage_r

    priors:
        ls:     --
        color:  grey

    scatter:
        marker: .
        # size:   1
        alpha:  0.75

    density:
        alpha:      0.75
        edgecolors: none

    figure:
        margins:
            hspace: 0.05
            wspace: 0.05

    ticks:
        labelrotation:  45
        pad:            0
        length:         2

    labels:
        labelpad:       15
        rotation:       0
        va:             center
        rotation_mode:  null